# permissions for end users to view kuberdons.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kuberdon-viewer-role
rules:
- apiGroups:
  - kuberdon.kuberty.io
  resources:
  - kuberdons
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kuberdon.kuberty.io
  resources:
  - kuberdons/status
  verbs:
  - get
