name: Go

on: [ push, pull_request]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
      
    - name: Check out the kubernetes project
      uses: actions/checkout@v2
      with:
        repository: kubernetes/kubernetes
        ref: v1.19.0-alpha.0 
        path: .
        
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        path: staging/src/github.com/kuberty/kuberdon

    - name: Install dependencies
      run: |
        echo "Installing kubebuilder..."
        echo "a8ffea619f8d6e6c9fab2df8543cf0912420568e3979f44340a7613de5944141 -" > kubebuildersum.txt
        curl -sfL https://github.com/kubernetes-sigs/kubebuilder/releases/download/v2.3.0/kubebuilder_2.3.0_linux_amd64.tar.gz | tee kubebuilder_2.3.0_linux_amd64.tar.gz | sha256sum -c kubebuildersum.txt
        tar -xf kubebuilder_2.3.0_linux_amd64.tar.gz
        sudo chmod +x kubebuilder_2.3.0_linux_amd64
        sudo mv kubebuilder_2.3.0_linux_amd64 /usr/local/kubebuilder
        echo "Installing kustomize..."
        echo "5cdeb2af81090ad428e3a94b39779b3e477e2bc946be1fe28714d1ca28502f6a -" > kustomize.txt
        curl -sfL https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv3.5.4/kustomize_v3.5.4_linux_amd64.tar.gz | tee kustomize_v3.5.4_linux_amd64.tar.gz | sha256sum -c kustomize.txt
        tar -xf kustomize_v3.5.4_linux_amd64.tar.gz
        sudo chmod +x kustomize
        sudo mv kustomize /usr/local/kustomize
    - name: Build
      run: | 
        export GOPATH=$PWD/staging
        cd staging/src/github.com/kuberty/kuberdon/
        make all
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
      
    - name: Check out the kubernetes project
      uses: actions/checkout@v2
      with:
        repository: kubernetes/kubernetes
        ref: v1.19.0-alpha.0 
        path: .
        
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        path: staging/src/github.com/kuberty/kuberdon

    - name: Install dependencies
      run: |
        echo "Installing kubebuilder..."
        echo "a8ffea619f8d6e6c9fab2df8543cf0912420568e3979f44340a7613de5944141 -" > kubebuildersum.txt
        curl -sfL https://github.com/kubernetes-sigs/kubebuilder/releases/download/v2.3.0/kubebuilder_2.3.0_linux_amd64.tar.gz | tee kubebuilder_2.3.0_linux_amd64.tar.gz | sha256sum -c kubebuildersum.txt
        tar -xf kubebuilder_2.3.0_linux_amd64.tar.gz
        sudo chmod +x kubebuilder_2.3.0_linux_amd64
        sudo mv kubebuilder_2.3.0_linux_amd64 /usr/local/kubebuilder
        echo "Installing kustomize..."
        echo "5cdeb2af81090ad428e3a94b39779b3e477e2bc946be1fe28714d1ca28502f6a -" > kustomize.txt
        curl -sfL https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv3.5.4/kustomize_v3.5.4_linux_amd64.tar.gz | tee kustomize_v3.5.4_linux_amd64.tar.gz | sha256sum -c kustomize.txt
        tar -xf kustomize_v3.5.4_linux_amd64.tar.gz
        sudo chmod +x kustomize
        sudo mv kustomize /usr/local/kustomize
    - name: Build
      run: | 
        export GOPATH=$PWD/staging
        cd staging/src/github.com/kuberty/kuberdon/
        make test
